server:
  port: "0.0.0.0:8080"

#database:
#  host: 10.48.1.213
#  port: 1433
#  user: sa
#  password: 188910
#  name: EF_RST_10000
#  timeout: 15
database:
  host:  s_n/SQLEXPRESS
  port: 1433
  user: sa
  password: 798246
  name: eplus_apteka_349_new
  timeout: 15


security:
  jwt_secret: supersecretkey